myQa/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from core.views import register, user_login, user_logout

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^register/$', register, name='register'),
    url(r'^login/$', user_login, name='login'),
    url(r'^logout/$', user_logout, name='logout'),
    url(r'^', include('myapp.urls')),
]

myapp/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.QuestionIndexView.as_view(), name='qa_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.AnswerQuestionView.as_view(), name='qa_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.CloseQuestionView.as_view(), name='qa_close_question'),

    url(r'^new-question/$', views.CreateQuestionView.as_view(),
        name='qa_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.UpdateQuestionView.as_view(),
        name='qa_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.CreateAnswerView.as_view(), name='qa_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.UpdateAnswerView.as_view(), name='qa_update_answer'),

    url(r'^vote/question/(?P<object_id>\d+)/$',
        views.QuestionVoteView.as_view(), name='qa_question_vote'),

    url(r'^vote/answer/(?P<object_id>\d+)/$',
        views.AnswerVoteView.as_view(), name='qa_answer_vote'),

    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.CreateAnswerCommentView.as_view(),
        name='qa_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.CreateQuestionCommentView.as_view(),
        name='qa_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.UpdateQuestionCommentView.as_view(),
        name='qa_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.UpdateAnswerCommentView.as_view(),
        name='qa_update_answer_comment'),

    url(r'^search/$', views.QuestionsSearchView.as_view(), name='qa_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QuestionsByTagView.as_view(), name='qa_tag'),

    url(r'^profile/(?P<user_id>\d+)/$', views.profile, name='qa_profile'),

    url('^markdown/', include('django_markdown.urls')),

    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]

myapp/models.py
from annoying.fields import AutoOneToOneField
from django.conf import settings
from django.db import models
from django.db.models import F
from django.utils.text import slugify
from django_markdown.models import MarkdownField
from hitcount.models import HitCountMixin
from taggit.managers import TaggableManager


class UserQAProfile(models.Model):
    """Model class to define a User profile for the app, directly linked
    to the core Django user model."""
    user = AutoOneToOneField(settings.AUTH_USER_MODEL, primary_key=True,
                             on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)

    def modify_reputation(self, added_points):
        """Core function to modify the reputation of the user profile."""
        self.points = F('points') + added_points
        self.save()

    def __str__(self):  # pragma: no cover
        return self.user.username


class Question(models.Model, HitCountMixin):
    """Model class to contain every question in the forum"""
    slug = models.SlugField(max_length=200)
    title = models.CharField(max_length=200, blank=False)
    description = MarkdownField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    tags = TaggableManager()
    reward = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    closed = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    class Meta:
        ordering = ['-pub_date']

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
            try:
                points = settings.QA_SETTINGS['reputation']['CREATE_QUESTION']

            except KeyError:
                points = 0

            self.user.userqaprofile.modify_reputation(points)

        self.total_points = self.positive_votes - self.negative_votes
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Answer(models.Model):
    """Model class to contain every answer in the forum and to link it
    to the proper question."""
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = MarkdownField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField('date updated', auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    answer = models.BooleanField(default=False)
    positive_votes = models.IntegerField(default=0)
    negative_votes = models.IntegerField(default=0)
    total_points = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_ANSWER']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        self.total_points = self.positive_votes - self.negative_votes
        super(Answer, self).save(*args, **kwargs)

    def __str__(self):  # pragma: no cover
        return self.answer_text

    class Meta:
        ordering = ['-answer', '-pub_date']


class VoteParent(models.Model):
    """Abstract model to define the basic elements to every single vote."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    value = models.BooleanField(default=True)

    class Meta:
        abstract = True


class AnswerVote(VoteParent):
    """Model class to contain the votes for the answers."""
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('user', 'answer'),)


class QuestionVote(VoteParent):
    """Model class to contain the votes for the questions."""
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('user', 'question'),)


class BaseComment(models.Model):
    """Abstract model to define the basic elements to every single comment."""
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):  # pragma: no cover
        return self.comment_text


class AnswerComment(BaseComment):
    """Model class to contain the comments for the answers."""
    comment_text = MarkdownField()
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_ANSWER_COMMENT']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        super(AnswerComment, self).save(*args, **kwargs)


class QuestionComment(BaseComment):
    """Model class to contain the comments for the questions."""
    comment_text = models.CharField(max_length=250)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        try:
            points = settings.QA_SETTINGS['reputation']['CREATE_QUESTION_COMMENT']

        except KeyError:
            points = 0

        self.user.userqaprofile.modify_reputation(points)
        super(QuestionComment, self).save(*args, **kwargs)

myapp/forms.py
from django import forms
from django.conf import settings
from myapp.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'description', 'tags']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'description': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)

        try:
            settings.QA_SETTINGS['qa_description_optional']
            self.fields['description'].required = not settings.QA_SETTINGS[
                'qa_description_optional']

        except KeyError:
            pass

myapp/templates/myapp/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="en">
  <head>
    <title>QA{% block title %}{% endblock title %}</title>
    <meta charset="UTF-8"/>
    <link rel="icon" type="image/png" href="static/qa/icon.ico">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <link href='//fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />
    <link href="{% static 'css/qa.css' %}" rel="stylesheet"/>


    <style media="screen">
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300&display=swap');
      hr{margin: 0px;}
      html, body {

          font-family: 'Montserrat', sans-serif;
          font-size: 13px;
          line-height: auto;
          /* color: rgb(40, 40, 41); */
          direction: ltr;
          background-color: white;
      }

      tag {
        border-radius: 3px;
        padding: 2px;
        margin: 1px;
        background-color: #E1ECF4;
        color: #39739D;

      }
      /* Dropdown Button */
      .dropbtn {
        background-color: transparent;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
      }

      /* The container <div> - needed to position the dropdown content */
      .dropdown {
        position: relative;
        display: inline-block;
      }

      /* Dropdown Content (Hidden by Default) */
      .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
      }

      /* Links inside the dropdown */
      .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
      }

      /* Change color of dropdown links on hover */
      .dropdown-content a:hover {background-color: #ddd;}

      /* Show the dropdown menu on hover */
      .dropdown:hover .dropdown-content {display: block;}

      /* Change the background color of the dropdown button when the dropdown content is shown */
      .dropdown:hover .dropbtn {background-color: #3e8e41;}
    </style>
  </head>
  <body>
    <!-- <div class="topbar"></div> -->
    <!-- Navbar -->
      <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <!-- Container wrapper -->
        <div class="container container-fluid">
          <!-- Toggle button -->
          <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <i class="fas fa-bars"></i>
          </button>

          <!-- Collapsible wrapper -->
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Navbar brand -->
            <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'qa_index' %}">
              <i class="far fa-question-circle" style="font-size: 25px;"> Q n A</i>
            </a>
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="/"><strong>Home</strong></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Team</a>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Projects</a>
              </li> -->
            </ul>
            <!-- Left links -->
          </div>
          <!-- Collapsible wrapper -->

          <!-- Right elements -->
          <div class="d-flex align-items-center">
            <!-- Icon -->
            <div class="search" style="margin-right: 5px;">
              <form method="GET" action="{% url 'qa_search' %}" class="input-group">
                  <input style="padding-left: 50px;" type="search" id="form1" value="" class="form-control" name="word" placeholder="search here..." aria-label="Search" />
                  <input type="submit" class="btn btn-primary" value="Search">
                </button>
              </form>
            </div>

            <!-- Notifications -->
            <a href="{% url 'qa_create_question' %}"  type="button" class="btn btn-dark" style="margin-right: 1em;">Ask Question</a>
            <!-- Avatar -->

          {% if user.is_authenticated %}
          <div class="dropdown">
            <button class="dropbtn">
              <img
                src="https://mdbootstrap.com/img/new/avatars/2.jpg"
                class="rounded-circle"
                height="25"
                alt=""
                loading="lazy"
              />
            </button>
            <div class="dropdown-content">
              <a href="#">My profile</a>
              <a href="#">Settings</a>
              <a href="/logout">Logout</a>
            </div>
          </div>
            {% else %}
              <div class="d-flex align-items-center">
                <a href="/login" type="button" class="btn btn-link px-3 me-2" style="color: black;">
                  Log In
                </a>
                <a href="/register" type="button" class="btn btn-dark">
                  Sign Up
                </a>
              </div>
            {% endif %}
          </div>
          <!-- Right elements -->
        </div>
        <!-- Container wrapper -->
      </nav>

    <div class="container">
      {% if messages %}
      {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
      {% endif %}

        {% block content %}

        {% endblock content %}

      <!-- <div id="search">

    	<button type="button" class="close">×</button>
    	<form method="GET" action="{% url 'qa_search' %}">
    	  <input type="search" value="" name="word" placeholder="type keyword(s) here" />
    	  <input class="btn btn-lg btn-warning" type="submit" value="Find" />
    	</form>

      </div> -->

    </div>
    <hr>
    <center>
      <small><a href="/admin">Admin Panel</a></small></center>
    <br/><br/>


    <!-- Modal -->
    <div class="modal fade" id="apiModal" tabindex="-1" role="dialog" aria-labelledby="APIModal" aria-hidden="true">
      <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span> API Access</h4>
	  </div>
	  <div class="modal-body">
            <ul>
              <li>
		<b>List of Questions</b>
		<br/>Retrieve the list of questions.
		<br/>json URL : <code class="custom-code">http://djangoqa.azurewebsites.net/api/questions/?format=json</code>
              </li>
              <br/>
              <li>
		<b>List of Users</b>
		<br/>Retrieve the list of users.
		<br/>json URL : <code class="custom-code">http://djangoqa.azurewebsites.net/api/users/?format=json</code>
              </li>
            </ul>
	  </div>
	  <div class="modal-footer">
            <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
	  </div>
	</div>
      </div>
    </div>

    {% block js %}
    <script>
      $(function () {
      $('a[href="#search"]').on('click', function(event) {
      event.preventDefault();
      $('#search').addClass('open');
      $('#search > form > input[type="search"]').focus();
      });

      $('#search, #search button.close').on('click keyup', function(event) {
      if (event.target == this || event.target.className == 'close' || event.keyCode == 27) {
      $(this).removeClass('open');
      }
      });

      });
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% endblock js %}
    {%block extra_js %}{% endblock extra_js %}
    <!-- MDB -->
  </body>
</html>

myapp/templates/myapp/create_answer.html
{% extends 'myapp/base.html' %}
{% load django_markdown %}

{% block content %}
<div class="container">

</div>
  {% if message %}
  <strong>Enter a valid Question!</strong>
  {% endif %}

  <form method="post" class="post-form" action="{% block action_url %}{% url 'qa_create_answer' view.kwargs.question_id %}{% endblock action_url %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn pull-right btn-success" type="submit" value="Submit Answer" />
  </form>
  <script>var editor = new MediumEditor('.editable');</script>


{% endblock content %}

{% block extra_js %}
  {% markdown_editor "#id_answer_text" %}
  {% markdown_media %}
{% endblock %}

myapp/templates/myapp/create_comment.html
{% extends 'myapp/base.html' %}
{% load django_markdown %}

{% block content %}

  {% if message %}
    <strong>Enter a valid Answer!</strong>
  {% endif %}

  <form method="post" class="post-form" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn pull-right btn-success" type="submit" value="Submit Comment" />
  </form>
    <script>var editor = new MediumEditor('.editable');</script>

{% markdown_editor "#ans" %}
{% markdown_media %}
{% endblock content %}

myapp/templates/myapp/create_question.html
{% extends 'myapp/base.html' %}
{% load django_markdown %}

{% block content %}
<div class="contaner">
  {% if message %}
  <strong>Enter a valid Question!</strong>
  {% endif %}

  <form method="post" action="{% block action_url %}{% url 'qa_create_question' %}{% endblock action_url %}">
    {% csrf_token %}
    {{ form.as_p }}

    <input class="btn pull-right btn-success" type="submit" value="Submit Question" />
  </form>
</div>
  <script>var editor = new MediumEditor('.editable');</script>



{% endblock content %}

{% block extra_js %}
  {% markdown_editor "#id_description" %}
  {% markdown_media %}
{% endblock extra_js %}

myapp/templates/myapp/detail_question.html
{% extends 'myapp/base.html' %}
{% load django_markdown %}
{% load staticfiles %}

{% block content %}

<div class="container" style="padding-left: 0px;border: 1px solid lightgray;">
  {% if question.closed %}
    <div class="closed"></div>
  {% else %}
      {% if question.reward %}
      <div class="rewarding"></div>
      {% else %}
      <div class="open"></div>
      {% endif %}
  {% endif %}


  {% if message %}
      <div class="alert alert-danger" role="alert">{{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
      </div>
  {% endif %}
  {% comment %}

  {% if question.reward %}
      <div class="alert alert-info" role="alert">This question has been marked to be worth a reward of <b>{{ question.reward }}<b> points!
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
      </div>
  {% endif %}
  {% endcomment %}

  <div class="container" style="padding: 0px;">
    <div class="row">
      <div class="d-flex flex-column mb-3">
      <div class="p-2">
        {% if user.is_authenticated and question.user != user %}

          <div class ="col-md-1 d-flex align-items-start flex-column mb-3">
            <form action="{% url 'qa_question_vote' question.id %}" method="POST" class="p-2">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <input type="hidden" name="upvote" value="on">
              <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer" style="margin: 0px;"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
            </form>
            <div class="p-2" style="margin-left: 15px;margin-right: 15px;">
              <big class="pull-left custom-big"><b>{{ question.total_points }}</b></big>
            </div>
              <form action="{% url 'qa_question_vote' question.id %}" method="POST" class="p-2">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer" style="margin: 0px;"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button>
            </form>
          </div>
        {% endif %}
        <div class="col-md-11" style="padding-left: 12px;padding-right: 0px;">
          <small class="pull-right" style="padding-right: 0px;">Posted by {{ question.user.username }}, {{ question.pub_date }}</small>
          {% if user.is_authenticated and question.user == user %}<a href="{% url 'qa_update_question' question.id %}"><small class="pull-right">Edit &nbsp;</small></a>{% endif %}
          <h3><cool>Q: </cool>{{ question.title }}</h3>
          <h4>{{ question.description|markdown }}</h4>
      </div>
      </div>
      <div class="p-2">
        {% if question.closed %}
            <p class="pull-right">This Question has been closed.</p>
        {% else %}
            <a class="btn btn-primary btn-sm pull-right" href="{% url 'qa_create_answer' question.id %}" role="button" style="margin-left: 5px;">Answer</a>
            <a class="btn btn-primary btn-sm pull-right" href="{% url 'qa_create_question_comment' question.id %}" role="button" style="margin-left: 5px;">Comment</a>
            <form action="{% url 'qa_close_question' question.id %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}"/>
              <button type="submit" class="btn btn-warning btn-sm pull-right" data-toggle="tooltip" data-placement="bottom">Close question</button>
            </form>
        {% endif %}
      </div>
    </div>

      </div>
    </div>
  </div>

  {% if last_comments %}
    <h4>comments</h4>
    {% for comment in last_comments %}
    <div class="row">
      <div class="col-md-9 col-md-offset-1">
      <p><b>{{ comment.comment_text|markdown }}</b><small>, <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_question_comment' comment.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
      </div>
    </div>
    {% endfor %}
  {% endif %}
  {% if answers %}
    <h3>Answers</h3>
    <hr/>

      {% for answer in answers %}
      <div class="row">
        {% if user.is_authenticated and answer.user != user %}
        <div class ="col-md-1">
          <div class="row">
            <div class ="col-sm-1"><big class="pull-left custom-big"><b>{{ answer.total_points }}</b></big></div>
            <div class ="col-sm-1">
            <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <input type="hidden" name="upvote" value="on">
                <button type="submit" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Vote Up this answer"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
            </form>
            <form action="{% url 'qa_answer_vote' answer.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button type="submit" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Vote Down this answer"><span class="glyphicon glyphicon-minus" aria-hidden="true"></span></button>
            </form>
            </div>
          </div>
        </div>
        {% endif %}
        <div class ="col-md-9">
          <a href="{% url 'qa_create_answer_comment' answer.id %}" class="pull-right"><small><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comment &nbsp;</small></a>
          {% if answer.user == user %}<a href="{% url 'qa_update_answer' answer.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
              <div id="ans" class="alert alert-primary" role="alert">{{ answer.answer_text|markdown }}</div>
          {% if answer.answercomment_set %}
            {% for comment in answer.answercomment_set.all %}
              <p><b>{{ comment.comment_text|markdown }}</b><small>, <a href="{% url 'qa_profile' comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa_update_answer_comment' comment.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
            <hr>
            {% endfor %}
          {% endif %}
        </div>
            <div class ="col-md-2">
              {% if answer.user.userqaprofile.picture %}
                  <img class="pull-right" src="{{ answer.user.userqaprofile.picture }}">
              {% else %}
                  <img class="pull-right" width="25px" height="25px" src="{% static "myapp/user.png" %}">
              {% endif %}
              <p class="pull-right">- <b><a href="{% url 'qa_profile' answer.user.id %}">{{ answer.user.username }}</a> ({{ answer.user.userqaprofile.points }})</b></p>
                  {% if user.is_authenticated and answer.question.user == user and answer.question.closed == False %}
                      <form action="{% url 'qa_answer_question' answer.id %}" method="POST">
                          {% csrf_token %}
                          <input type="hidden" name="next" value="{{ request.path }}"/>
                          <button type="submit" class="btn btn-success btn-sm pull-right" data-toggle="tooltip" data-placement="bottom" title="Mark as answer"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button></div>
                      </form>
                  {% else %}
                      {% if  answer.answer == True %}
                          <button class="btn btn-success btn-sm pull-right" title="Picked Answer"><span class="glyphicon glyphicon-star" aria-hidden="true"></span></button></div>
                      {% endif %}
                  {% endif %}

    <hr>
      {% endfor %}

  {% else %}
  <center><h2>This question is still open, <a href="{% url 'qa_create_answer' question.id %}" role="button">Write answer!</a></h2></center>
  {% endif %}

</div>


{% endblock content %}
{% block extra_js %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock extra_js %}

myapp/templates/myapp/update_answer.html
{% extends 'myapp/create_answer.html' %}

{% block action_url %}
{% url 'qa_update_answer' view.kwargs.answer_id %}
{% endblock action_url %}